events {}

http {
  limit_req_zone $binary_remote_addr zone=api:10m rate=20r/s;
  server_tokens off;

  upstream journey { server customer-journey:8080; }
  upstream intelligence { server vehicle-intelligence:8000; }
  upstream workshop { server workshop-operations:8080; }

  server {
    listen 8080;
    client_max_body_size 1m;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;

    location /journey/ {
      limit_req zone=api burst=40 nodelay;
      proxy_pass http://journey/;
      proxy_set_header X-Request-ID $request_id;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /intelligence/ {
      limit_req zone=api burst=40 nodelay;
      proxy_pass http://intelligence/;
      proxy_set_header X-Request-ID $request_id;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /workshop/ {
      limit_req zone=api burst=40 nodelay;
      proxy_pass http://workshop/;
      proxy_set_header X-Request-ID $request_id;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}

